
create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  title text not null,
  description text not null default '',
  due_date date not null,
  priority text not null default 'Medium' check (priority in ('High', 'Medium', 'Low')),
  status text not null default 'Pending' check (status in ('Pending', 'Completed')),
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('Math', 'Science', 'Programming', 'English')),
  score integer not null check (score between 0 and 10),
  total integer not null default 10 check (total = 10),
  best_streak integer not null default 0 check (best_streak between 0 and 10),
  created_at timestamptz not null default now()
);

alter table public.courses enable row level security;
alter table public.assignments enable row level security;
alter table public.quiz_results enable row level security;

drop policy if exists "Users manage their own courses" on public.courses;
create policy "Users manage their own courses"
on public.courses for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage their own assignments" on public.assignments;
create policy "Users manage their own assignments"
on public.assignments for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage their own quiz results" on public.quiz_results;
create policy "Users manage their own quiz results"
on public.quiz_results for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create index if not exists courses_user_id_idx on public.courses(user_id);
create index if not exists assignments_user_id_idx on public.assignments(user_id);
create index if not exists assignments_course_id_idx on public.assignments(course_id);
create index if not exists assignments_due_date_idx on public.assignments(due_date);
create index if not exists quiz_results_user_id_idx on public.quiz_results(user_id);
create index if not exists quiz_results_score_idx on public.quiz_results(user_id, score desc);
